# Generated by Django 5.0.7 on 2024-09-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('documentId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('writer', models.CharField(max_length=32)),
                ('file', models.FileField(upload_to='documents/')),
                ('content', models.TextField()),
                ('regDate', models.DateTimeField(auto_now_add=True)),
                ('updDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
