# Generated by Django 5.0.7 on 2024-08-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="password",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name="accountlogintype",
            name="loginType",
            field=models.CharField(
                choices=[("KAKAO", "Kakao"), ("NORMAL", "normal")], max_length=10
            ),
        ),
    ]
