# Generated by Django 5.0.7 on 2024-08-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_profile_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountlogintype",
            name="loginType",
            field=models.CharField(
                choices=[
                    ("KAKAO", "Kakao"),
                    ("NORMAL", "normal"),
                    ("GOOGLE", "google"),
                ],
                max_length=10,
            ),
        ),
    ]
