# Generated by Django 5.0.7 on 2024-08-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_accountlogintype_logintype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilegendertype",
            name="gender_type",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=10,
                unique=True,
            ),
        ),
    ]
