# Generated by Django 5.0.7 on 2024-08-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_profilegendertype_gender_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountlogintype",
            name="loginType",
            field=models.CharField(
                choices=[
                    ("KAKAO", "Kakao"),
                    ("NORMAL", "normal"),
                    ("GOOGLE", "google"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="accountroletype",
            name="roleType",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("NORMAL", "Normal"),
                    ("BLACKLIST", "Blacklist"),
                ],
                default="NORMAL",
                max_length=64,
                unique=True,
            ),
        ),
    ]
