# Generated by Django 5.0.7 on 2024-08-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_accountlogintype_logintype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="salt",
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
