# Generated by Django 5.0.7 on 2024-09-02 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='view_count', to='community.community')),
            ],
            options={
                'db_table': 'community_viewcount',
            },
        ),
    ]
